/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* top =  1  *)
(* src = "fsm_synth.v:1" *)
module fsm_synth(clk, reset, data_input, err, nxt_err);
  (* src = "fsm_synth.v:23" *)
  wire [3:0] _000_;
  (* src = "fsm_synth.v:23" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "fsm_synth.v:3" *)
  input clk;
  (* src = "fsm_synth.v:14" *)
  wire [3:0] counter;
  (* src = "fsm_synth.v:5" *)
  input [15:0] data_input;
  (* src = "fsm_synth.v:6" *)
  output err;
  (* src = "fsm_synth.v:7" *)
  output nxt_err;
  (* src = "fsm_synth.v:4" *)
  input reset;
  (* onehot = 32'd1 *)
  wire [4:0] state;
  NOT _082_ (
    .A(state[2]),
    .Y(_016_)
  );
  NOT _083_ (
    .A(reset),
    .Y(_017_)
  );
  NOT _084_ (
    .A(counter[2]),
    .Y(_018_)
  );
  NOT _085_ (
    .A(data_input[2]),
    .Y(_019_)
  );
  NOT _086_ (
    .A(data_input[3]),
    .Y(_020_)
  );
  NOT _087_ (
    .A(counter[3]),
    .Y(_021_)
  );
  NAND _088_ (
    .A(data_input[12]),
    .B(data_input[13]),
    .Y(_022_)
  );
  NAND _089_ (
    .A(data_input[14]),
    .B(data_input[15]),
    .Y(_023_)
  );
  NOR _090_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOT _091_ (
    .A(_024_),
    .Y(_025_)
  );
  NAND _092_ (
    .A(counter[1]),
    .B(data_input[1]),
    .Y(_027_)
  );
  NOT _093_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _094_ (
    .A(counter[1]),
    .B(data_input[1]),
    .Y(_029_)
  );
  NOT _095_ (
    .A(_029_),
    .Y(_030_)
  );
  NAND _096_ (
    .A(_027_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _097_ (
    .A(_028_),
    .B(_029_),
    .Y(_033_)
  );
  NAND _098_ (
    .A(counter[0]),
    .B(data_input[0]),
    .Y(_034_)
  );
  NOT _099_ (
    .A(_034_),
    .Y(_035_)
  );
  NOR _100_ (
    .A(counter[0]),
    .B(data_input[0]),
    .Y(_037_)
  );
  NOT _101_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _102_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _103_ (
    .A(_035_),
    .B(_037_),
    .Y(_040_)
  );
  NOR _104_ (
    .A(_033_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _105_ (
    .A(_031_),
    .B(_039_),
    .Y(_042_)
  );
  NOR _106_ (
    .A(_020_),
    .B(counter[3]),
    .Y(_043_)
  );
  NAND _107_ (
    .A(data_input[3]),
    .B(_021_),
    .Y(_044_)
  );
  NOR _108_ (
    .A(data_input[3]),
    .B(_021_),
    .Y(_045_)
  );
  NAND _109_ (
    .A(_020_),
    .B(counter[3]),
    .Y(_046_)
  );
  NOR _110_ (
    .A(_043_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _111_ (
    .A(_044_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _112_ (
    .A(_018_),
    .B(data_input[2]),
    .Y(_049_)
  );
  NAND _113_ (
    .A(counter[2]),
    .B(_019_),
    .Y(_050_)
  );
  NOR _114_ (
    .A(counter[2]),
    .B(_019_),
    .Y(_051_)
  );
  NAND _115_ (
    .A(_018_),
    .B(data_input[2]),
    .Y(_052_)
  );
  NOR _116_ (
    .A(_049_),
    .B(_051_),
    .Y(_053_)
  );
  NAND _117_ (
    .A(_050_),
    .B(_052_),
    .Y(_054_)
  );
  NOR _118_ (
    .A(_048_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _119_ (
    .A(_047_),
    .B(_053_),
    .Y(_056_)
  );
  NOR _120_ (
    .A(_042_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _121_ (
    .A(_041_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _122_ (
    .A(_025_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _123_ (
    .A(_024_),
    .B(_057_),
    .Y(_060_)
  );
  NAND _124_ (
    .A(reset),
    .B(_059_),
    .Y(_061_)
  );
  NAND _125_ (
    .A(state[0]),
    .B(_060_),
    .Y(_062_)
  );
  NAND _126_ (
    .A(reset),
    .B(_062_),
    .Y(_014_)
  );
  NOR _127_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_063_)
  );
  NOT _128_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _129_ (
    .A(state[0]),
    .B(_064_),
    .Y(_065_)
  );
  NOR _130_ (
    .A(_061_),
    .B(_065_),
    .Y(_015_)
  );
  NOR _131_ (
    .A(state[4]),
    .B(state[3]),
    .Y(_066_)
  );
  NOT _132_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _133_ (
    .A(_061_),
    .B(_066_),
    .Y(_026_)
  );
  NOR _134_ (
    .A(state[1]),
    .B(_067_),
    .Y(_068_)
  );
  NOR _135_ (
    .A(_025_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _136_ (
    .A(state[2]),
    .B(_069_),
    .Y(_070_)
  );
  NAND _137_ (
    .A(reset),
    .B(_058_),
    .Y(_071_)
  );
  NOR _138_ (
    .A(_070_),
    .B(_071_),
    .Y(_032_)
  );
  NOR _139_ (
    .A(_024_),
    .B(_068_),
    .Y(_072_)
  );
  NOR _140_ (
    .A(_016_),
    .B(_058_),
    .Y(_073_)
  );
  NOR _141_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _142_ (
    .A(reset),
    .B(_060_),
    .Y(_075_)
  );
  NOR _143_ (
    .A(_074_),
    .B(_075_),
    .Y(_036_)
  );
  NAND _144_ (
    .A(state[0]),
    .B(err),
    .Y(_076_)
  );
  NOT _145_ (
    .A(_076_),
    .Y(_077_)
  );
  NOR _146_ (
    .A(state[2]),
    .B(_077_),
    .Y(_078_)
  );
  NAND _147_ (
    .A(_068_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _148_ (
    .A(_060_),
    .B(_079_),
    .Y(_080_)
  );
  NOT _149_ (
    .A(_080_),
    .Y(nxt_err)
  );
  NAND _150_ (
    .A(reset),
    .B(_080_),
    .Y(_081_)
  );
  NOR _151_ (
    .A(counter[0]),
    .B(_081_),
    .Y(_000_[0])
  );
  NAND _152_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_002_)
  );
  NOT _153_ (
    .A(_002_),
    .Y(_003_)
  );
  NOR _154_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_004_)
  );
  NOT _155_ (
    .A(_004_),
    .Y(_005_)
  );
  NAND _156_ (
    .A(_002_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _157_ (
    .A(_081_),
    .B(_006_),
    .Y(_000_[1])
  );
  NAND _158_ (
    .A(counter[2]),
    .B(_003_),
    .Y(_007_)
  );
  NAND _159_ (
    .A(_018_),
    .B(_002_),
    .Y(_008_)
  );
  NAND _160_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _161_ (
    .A(_081_),
    .B(_009_),
    .Y(_000_[2])
  );
  NAND _162_ (
    .A(counter[3]),
    .B(_007_),
    .Y(_010_)
  );
  NOT _163_ (
    .A(_010_),
    .Y(_011_)
  );
  NOR _164_ (
    .A(counter[3]),
    .B(_007_),
    .Y(_012_)
  );
  NOR _165_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _166_ (
    .A(_081_),
    .B(_013_),
    .Y(_000_[3])
  );
  NOR _167_ (
    .A(_017_),
    .B(_080_),
    .Y(_001_)
  );
  DFF _168_ (
    .C(clk),
    .D(_014_),
    .Q(state[0])
  );
  DFF _169_ (
    .C(clk),
    .D(_032_),
    .Q(state[1])
  );
  DFF _170_ (
    .C(clk),
    .D(_036_),
    .Q(state[2])
  );
  DFF _171_ (
    .C(clk),
    .D(_026_),
    .Q(state[3])
  );
  DFF _172_ (
    .C(clk),
    .D(_015_),
    .Q(state[4])
  );
  (* src = "fsm_synth.v:23" *)
  DFF _173_ (
    .C(clk),
    .D(_001_),
    .Q(err)
  );
  (* src = "fsm_synth.v:23" *)
  DFF _174_ (
    .C(clk),
    .D(_000_[0]),
    .Q(counter[0])
  );
  (* src = "fsm_synth.v:23" *)
  DFF _175_ (
    .C(clk),
    .D(_000_[1]),
    .Q(counter[1])
  );
  (* src = "fsm_synth.v:23" *)
  DFF _176_ (
    .C(clk),
    .D(_000_[2]),
    .Q(counter[2])
  );
  (* src = "fsm_synth.v:23" *)
  DFF _177_ (
    .C(clk),
    .D(_000_[3]),
    .Q(counter[3])
  );
endmodule
